"""
LLM/VLM Impedance Planner for contact-rich manipulation.
Given task state, returns a stiffness prior (log-space SPD hint)
that biases the RL policy's action distribution.

Backend options (set via `backend` arg):
  "openai"  -- OpenAI API (GPT-4o, GPT-4o-mini, etc.)  needs OPENAI_API_KEY
  "ollama"  -- Local Ollama server (llama3.2, mistral, etc.) no key needed
               Install: https://ollama.com  then `ollama pull llama3.2`

Profile loading
───────────────
Pass `profile_path` to load impedance modes and the system prompt from a YAML
file generated by `hires_vic/llm/profile_generator.py`.  Falls back to the
built-in wipe modes if no profile is given (backwards-compatible).

Examples
────────
  LLMImpedancePlanner(backend="openai", model="gpt-4o-mini")
  LLMImpedancePlanner(backend="ollama", model="llama3.2")
  LLMImpedancePlanner(backend="openai", profile_path="configs/pih_impedance_profile.yaml")
"""
import math
import time 
import os
import threading
import numpy as np
import yaml
import re
import base64
import io
from dataclasses import dataclass
from openai import OpenAI
from dotenv import load_dotenv

try:
    from PIL import Image
except ImportError:
    Image = None

load_dotenv()

# Conversion helpers: physical stiffness values → normalised [-1,1] policy action space
# Inverse of the scaling applied in GeometricWrapper.step():
#   translational: log_kp = 0.5*(a+1)*log(300)  →  a = 2*log(Kp)/log(300) - 1
#   rotational:    kp     = 1 + 0.5*(a+1)*299   →  a = 2*(Kp-1)/299 - 1
_LOG300 = math.log(300)

def _kp_trans_to_norm_log(kp: float) -> float:
    """Physical translational stiffness (N/m) → [-1,1] policy action. Valid range: [1, 300]."""
    return 2.0 * math.log(max(kp, 1e-6)) / _LOG300 - 1.0

def _kp_trans_to_norm_linear(kp: float) -> float:
    """For BASELINE / LIE_GROUP (Linear space)"""
    return 2.0 * (kp - 1.0) / (300-1) - 1.0

def _kp_rot_to_norm(kp: float) -> float:
    """Physical rotational stiffness (N·m/rad) → [-1,1] policy action. Valid range: [1, 300]."""
    return 2.0 * (kp - 1.0) / (300-1) - 1.0

def _mode_to_action_prior(kp_trans: list, kp_rot: list, use_log_space: bool) -> np.ndarray:   
    """Convert physical stiffness dicts to a 9-dim normalised action 
    Layout: [m11, m22, m33, m12, m13, m23, kp_rot_x, kp_rot_y, kp_rot_z]
    Off-diagonal Mandel params set to 0 (no coupling prior).
    """
    trans_fn = _kp_trans_to_norm_log if use_log_space else _kp_trans_to_norm_linear
    
    return np.array([
        trans_fn(kp_trans[0]),
        trans_fn(kp_trans[1]),
        trans_fn(kp_trans[2]),
        0.0, 0.0, 0.0,
        _kp_rot_to_norm(kp_rot[0]),
        _kp_rot_to_norm(kp_rot[1]),
        _kp_rot_to_norm(kp_rot[2]),
    ])


def _load_profile(profile_path: str) -> tuple[dict, str]:
    """Load impedance modes and system prompt from a YAML profile."""
    with open(profile_path) as f:
        profile = yaml.safe_load(f)

    phases = profile.get("phases", {})
    system_prompt = profile.get("planner_prompt", None)

    modes = {}
    for name, cfg in phases.items():
        modes[name] = {
            "kp_trans": cfg["kp_trans"],
            "kp_rot":   cfg["kp_rot"],
            "description": cfg.get("description", ""),
        }

    return modes, system_prompt


def _build_modes(raw_modes: dict, use_log_space: bool) -> dict:
    out = {}
    for name, m in raw_modes.items():
        out[name] = dict(m)
        out[name]["action_prior"] = _mode_to_action_prior(m["kp_trans"], m["kp_rot"], use_log_space)
    return out


@dataclass
class ImpedanceSuggestion:
    mode: str
    action_prior: np.ndarray  # 9-dim in [-1,1]: [6 Mandel params, 3 kp_rot]
    confidence: float          # blend weight w: action = (1-w)*rl + w*prior


BACKEND_DEFAULTS = {
    "openai": "gpt-4o-mini",
    "ollama": "llama3.2",
}


class LLMImpedancePlanner:
    """
    Periodically queries an LLM to select an impedance mode based on
    task state description. Between queries, holds last suggestion.

    If `profile_path` is provided, loads modes and system prompt from that
    YAML file (generated by profile_generator.py).  Otherwise falls back to
    the built-in Wipe modes for backwards compatibility.
    """
    def __init__(
        self,
        backend: str = "openai",
        model: str | None = None,
        query_every_n_steps: int = 50,
        prior_weight: float = 0.4,
        profile_path: str | None = None,
        use_spd_manifold: bool = True,
        use_vision: bool = False,
        image_size: tuple = (224, 224),
    ):
        self.model = model or BACKEND_DEFAULTS[backend]
        self.query_every = query_every_n_steps
        self.prior_weight = prior_weight
        self.use_vision = use_vision
        self.image_size = image_size
        self._step = 0
        self._history: list[dict] = []
        self._query_in_flight = False
        self._ep_query_count = 0
        self._ep_total_llm_time = 0.0
        self._last_latency = 0.0

        if profile_path is not None:
            raw_modes, self._system_prompt = _load_profile(profile_path)
            print(f"[LLMImpedancePlanner] Loaded profile from {profile_path} "
                  f"({len(raw_modes)} phases: {list(raw_modes.keys())}) with spd_manifold={use_spd_manifold} vision={use_vision}.")
        else:
            print('[LLMImpedancePlanner] No profile_path provided, exiting...')
            return
            # raw_modes = _WIPE_IMPEDANCE_MODES
            # self._system_prompt = _WIPE_SYSTEM_PROMPT
            # print("[LLMImpedancePlanner] Using built-in Wipe impedance modes.")

        self._modes = _build_modes(raw_modes, use_spd_manifold)
        self._mode_names = list(self._modes.keys())
        self._last = self._default_suggestion()

        if backend == "ollama":
            ollama_host = os.environ.get("OLLAMA_HOST", "127.0.0.1:11434")
    
            # Format it exactly how the OpenAI client expects
            dynamic_base_url = f"http://{ollama_host}/v1"

            print(f'Ollama hosted at {dynamic_base_url}')
            
            self.client = OpenAI(base_url=dynamic_base_url, api_key="ollama")
        else:
            self.client = OpenAI()

    def _parse_mode_string(self, mode_str: str) -> str:
        """Robustly extract mode name from potentially messy LLM output."""
        # Strip punctuation and extra whitespace
        mode_str = re.sub(r'[^\w\s]', '', mode_str).strip().lower()
        
        # Try exact match first
        if mode_str in self._modes:
            return mode_str
        
        # Try substring matching for known phases
        for known_mode in self._mode_names:
            if known_mode in mode_str:
                return known_mode
        
        # If first word is a known mode
        first_word = mode_str.split()[0] if mode_str else ""
        if first_word in self._modes:
            return first_word
        
        # Default to first mode
        return self._mode_names[0]

    def _encode_image_to_base64(self, image_array: np.ndarray) -> str:
        """Convert numpy image array to base64 JPEG for API submission."""
        if Image is None:
            print("[LLMImpedancePlanner] PIL not installed, skipping image encoding")
            return ""
        
        try:
            # Ensure image is in uint8 format
            if image_array.dtype == np.float32 or image_array.dtype == np.float64:
                image_array = (np.clip(image_array, 0, 1) * 255).astype(np.uint8)
            else:
                image_array = np.clip(image_array, 0, 255).astype(np.uint8)
            
            # Resize if needed
            if image_array.shape[:2] != self.image_size:
                image_pil = Image.fromarray(image_array)
                image_pil = image_pil.resize(self.image_size, Image.Resampling.LANCZOS)
            else:
                image_pil = Image.fromarray(image_array)
            
            # Convert to JPEG bytes
            buffered = io.BytesIO()
            image_pil.save(buffered, format="JPEG", quality=85)
            img_str = base64.b64encode(buffered.getvalue()).decode()
            return img_str
        except Exception as e:
            print(f"[LLMImpedancePlanner] Image encoding failed: {e}")
            return ""

    def _fetch_async(self, state_desc: str):
        """Runs in a background thread. Updates self._last when done."""
        start_time = time.time()
        user_msg = f"Current robot state:\n{state_desc}\n\nWhich impedance mode?"
        history_snapshot = self._history + [{"role": "user", "content": user_msg}]
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                max_tokens=20,
                temperature=0,
                messages=[{"role": "system", "content": self._system_prompt}] + history_snapshot,
            )
            mode_str = response.choices[0].message.content.strip().lower()
            mode_str = self._parse_mode_string(mode_str)
            print(f"[LLMImpedancePlanner] LLM response: '{mode_str}' in {time.time() - start_time:.2f}s")
            if mode_str not in self._modes:
                mode_str = self._mode_names[0]
        except Exception as e:
            print(f"[LLMImpedancePlanner] Query failed: {e}")
            mode_str = self._last.mode
        
        end_time = time.time()
        latency = end_time - start_time
        self._last_latency = latency
        self._ep_total_llm_time += latency
        self._ep_query_count += 1

        self._history = history_snapshot + [{"role": "assistant", "content": mode_str}]
        if len(self._history) > 20:
            self._history = self._history[-20:]

        m = self._modes[mode_str]
        self._last = ImpedanceSuggestion(
            mode=mode_str,
            action_prior=m["action_prior"].copy(),
            confidence=self.prior_weight,
        )
        self._query_in_flight = False

    def _fetch_async_vision(self, state_desc: str, wrist_image: np.ndarray | None = None, view_image: np.ndarray | None = None):
        """Runs in a background thread with vision. Updates self._last when done."""
        start_time = time.time()
        
        try:
            if wrist_image is not None or view_image is not None:
                # Build multimodal message
                user_content = []
                
                # Add text
                user_content.append({
                    "type": "text",
                    "text": f"Current robot state:\n{state_desc}\n\nAnalyze the images and select the best impedance mode."
                })
                
                # Add wrist image
                if wrist_image is not None:
                    img_b64 = self._encode_image_to_base64(wrist_image)
                    if img_b64:
                        user_content.append({
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/jpeg;base64,{img_b64}",
                                "detail": "low"
                            }
                        })
                
                # Add 3rd person image
                if view_image is not None:
                    img_b64 = self._encode_image_to_base64(view_image)
                    if img_b64:
                        user_content.append({
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/jpeg;base64,{img_b64}",
                                "detail": "low"
                            }
                        })
                
                messages = [{"role": "system", "content": self._system_prompt}]
                messages += self._history
                messages.append({"role": "user", "content": user_content})
            else:
                # Fallback to text-only
                user_msg = f"Current robot state:\n{state_desc}\n\nWhich impedance mode?"
                messages = [{"role": "system", "content": self._system_prompt}]
                messages += self._history
                messages.append({"role": "user", "content": user_msg})
            
            response = self.client.chat.completions.create(
                model=self.model,
                max_tokens=20,
                temperature=0,
                messages=messages,
            )
            mode_str = response.choices[0].message.content.strip().lower()
            mode_str = self._parse_mode_string(mode_str)
            # print(f"[LLMImpedancePlanner] VLM response: '{mode_str}' in {time.time() - start_time:.2f}s")
            if mode_str not in self._modes:
                mode_str = self._mode_names[0]
        except Exception as e:
            print(f"[LLMImpedancePlanner] VLM query failed: {e}")
            mode_str = self._last.mode
        
        end_time = time.time()
        latency = end_time - start_time
        self._last_latency = latency
        self._ep_total_llm_time += latency
        self._ep_query_count += 1

        self._history.append({"role": "user", "content": "images received"})
        self._history.append({"role": "assistant", "content": mode_str})
        if len(self._history) > 20:
            self._history = self._history[-20:]

        m = self._modes[mode_str]
        self._last = ImpedanceSuggestion(
            mode=mode_str,
            action_prior=m["action_prior"].copy(),
            confidence=self.prior_weight,
        )
        self._query_in_flight = False

    def _default_suggestion(self) -> ImpedanceSuggestion:
        first = self._mode_names[0]
        m = self._modes[first]
        return ImpedanceSuggestion(first, m["action_prior"].copy(), 0.3)

    def _build_state_description(self, obs_dict: dict) -> str:
        """Convert obs dict to text for the LLM. Handles both Wipe and PiH keys."""
        lines = []

        eef_pos = obs_dict.get("robot0_eef_pos", np.zeros(3))
        lines.append(f"EEF position (xyz): [{eef_pos[0]:.3f}, {eef_pos[1]:.3f}, {eef_pos[2]:.3f}]")

        contact = bool(obs_dict.get("robot0_contact", obs_dict.get("is_contact", False)))
        lines.append(f"In contact: {contact}")

        if "proportion_wiped" in obs_dict:
            pw = float(obs_dict["proportion_wiped"])
            lines.append(f"Wipe completion: {pw * 100:.1f}%")
            dist = float(np.linalg.norm(obs_dict.get("gripper_to_wipe_centroid", np.zeros(3))))
            lines.append(f"Distance to wipe centroid: {dist:.4f} m")

        if "peg_head_pos" in obs_dict:
            ph = np.array(obs_dict["peg_head_pos"])
            lines.append(f"Peg head vs hole: [{ph[0]:.3f}, {ph[1]:.3f}, {ph[2]:.3f}]")
        if "insertion_depth" in obs_dict:
            lines.append(f"Insertion depth (0=none, 1=full): {obs_dict['insertion_depth']:.3f}")

        return "\n".join(lines)

    def query(self, obs_dict: dict, wrist_image: np.ndarray | None = None, view_image: np.ndarray | None = None) -> ImpedanceSuggestion:
        """Non-blocking query. Returns last suggestion immediately.
        
        Args:
            obs_dict: Dictionary of observations
            wrist_image: Optional wrist camera RGB image (numpy array)
            view_image: Optional 3rd-person camera RGB image (numpy array)
        """
        self._step += 1
        if self._step % self.query_every == 0 and not self._query_in_flight:
            self._query_in_flight = True
            state_desc = self._build_state_description(obs_dict)
            
            if self.use_vision and (wrist_image is not None or view_image is not None):
                t = threading.Thread(
                    target=self._fetch_async_vision,
                    args=(state_desc, wrist_image, view_image),
                    daemon=True
                )
            else:
                t = threading.Thread(target=self._fetch_async, args=(state_desc,), daemon=True)
            t.start()
        return self._last

    def reset(self):
        """Call at episode start to reset conversation context."""
        self._history = []
        self._last = self._default_suggestion()
        self._step = 0
        self._query_in_flight = False

        self._ep_query_count = 0
        self._ep_total_llm_time = 0.0
        self._last_latency = 0.0

    @property
    def mode_names(self) -> list[str]:
        return self._mode_names
    
    def get_episode_stats(self) -> dict:
        avg_latency = 0.0
        if self._ep_query_count > 0:
            avg_latency = self._ep_total_llm_time / self._ep_query_count
            
        return {
            "llm/total_queries": self._ep_query_count,
            "llm/total_latency_seconds": self._ep_total_llm_time,
            "llm/avg_latency_seconds": avg_latency
        }
