"""
LLM/VLM Impedance Planner for contact-rich manipulation.
Given task state, returns a stiffness prior (log-space SPD hint)
that biases the RL policy's action distribution.

Backend options (set via `backend` arg):
  "openai"  -- OpenAI API (GPT-4o, GPT-4o-mini, etc.)  needs OPENAI_API_KEY
  "ollama"  -- Local Ollama server (llama3.2, mistral, etc.) no key needed
               Install: https://ollama.com  then `ollama pull llama3.2`

Profile loading
───────────────
Pass `profile_path` to load impedance modes and the system prompt from a YAML
file generated by `hires_vic/llm/profile_generator.py`.  Falls back to the
built-in wipe modes if no profile is given (backwards-compatible).

Prior-weight schedule (new)
────────────────────────────
The effective prior weight w_eff is computed per-step from three sources,
applied in this priority order:
  1. Linear annealing  — w_eff = w * max(0, 1 - global_step / anneal_steps)
                          Fades the prior to zero over training so RL takes over.
                          Pass anneal_steps=0 to disable (default).
  2. Phase-transition boost — on a detected phase switch, temporarily multiply
                          w_eff by `transition_boost_mult` for `transition_boost_steps`
                          control steps, then resume normal schedule.
  3. Stability reduction — after `n_stable_reduce` consecutive same-phase steps,
                          reduce w_eff linearly toward 50% of nominal to prevent
                          the prior from clamping the RL agent once it has settled.

Examples
────────
  LLMImpedancePlanner(backend="openai", model="gpt-4o-mini")
  LLMImpedancePlanner(backend="ollama", model="llama3.2")
  LLMImpedancePlanner(backend="openai", profile_path="configs/pih_impedance_profile.yaml",
                      anneal_steps=100_000, transition_boost_mult=1.5)
"""
import math
import time
import os
import threading
import numpy as np
import yaml
import re
import base64
import io
from dataclasses import dataclass
from openai import OpenAI
from dotenv import load_dotenv

try:
    from PIL import Image
except ImportError:
    Image = None

load_dotenv()

# ── Conversion helpers ────────────────────────────────────────────────────────
# Physical stiffness values → normalised [-1,1] policy action space.
# Inverse of the scaling applied in GeometricWrapper.step():
#   translational: log_kp = 0.5*(a+1)*log(300)  →  a = 2*log(Kp)/log(300) - 1
#   rotational:    kp     = 1 + 0.5*(a+1)*299   →  a = 2*(Kp-1)/299 - 1
_LOG300 = math.log(300)


def _kp_trans_to_norm_log(kp: float) -> float:
    """Physical translational stiffness (N/m) → [-1,1] policy action. Valid range: [1, 300]."""
    return 2.0 * math.log(max(kp, 1e-6)) / _LOG300 - 1.0


def _kp_trans_to_norm_linear(kp: float) -> float:
    """For BASELINE / LIE_GROUP (Linear space)."""
    return 2.0 * (kp - 1.0) / (300 - 1) - 1.0


def _kp_rot_to_norm(kp: float) -> float:
    """Physical rotational stiffness (N·m/rad) → [-1,1] policy action. Valid range: [1, 300]."""
    return 2.0 * (kp - 1.0) / (300 - 1) - 1.0


def _mode_to_action_prior(kp_trans: list, kp_rot: list, use_log_space: bool) -> np.ndarray:
    """Convert physical stiffness dicts to a 9-dim or 6-dim normalised action.

    Layout if use_spd_manifold (log_space): [m11, m22, m33, m12, m13, m23, kp_rot_x, kp_rot_y, kp_rot_z]
    Layout otherwise: [kp_trans_x, kp_trans_y, kp_trans_z, kp_rot_x, kp_rot_y, kp_rot_z]
    """
    trans_fn = _kp_trans_to_norm_log if use_log_space else _kp_trans_to_norm_linear
    
    if use_log_space:
        return np.array([
            trans_fn(kp_trans[0]),
            trans_fn(kp_trans[1]),
            trans_fn(kp_trans[2]),
            0.0, 0.0, 0.0,  # off-diagonal: no coupling prior
            _kp_rot_to_norm(kp_rot[0]),
            _kp_rot_to_norm(kp_rot[1]),
            _kp_rot_to_norm(kp_rot[2]),
        ])
    else:
        return np.array([
            trans_fn(kp_trans[0]),
            trans_fn(kp_trans[1]),
            trans_fn(kp_trans[2]),
            _kp_rot_to_norm(kp_rot[0]),
            _kp_rot_to_norm(kp_rot[1]),
            _kp_rot_to_norm(kp_rot[2]),
        ])


def _load_profile(profile_path: str) -> tuple[dict, str]:
    """Load impedance modes and system prompt from a YAML profile."""
    with open(profile_path) as f:
        profile = yaml.safe_load(f)

    phases = profile.get("phases", {})
    system_prompt = profile.get("planner_prompt", None)

    modes = {}
    for name, cfg in phases.items():
        modes[name] = {
            "kp_trans": cfg["kp_trans"],
            "kp_rot":   cfg["kp_rot"],
            "description": cfg.get("description", ""),
        }

    return modes, system_prompt


def _build_modes(raw_modes: dict, use_log_space: bool) -> dict:
    out = {}
    for name, m in raw_modes.items():
        out[name] = dict(m)
        out[name]["action_prior"] = _mode_to_action_prior(m["kp_trans"], m["kp_rot"], use_log_space)
    return out


@dataclass
class ImpedanceSuggestion:
    mode: str
    action_prior: np.ndarray  # 9-dim in [-1,1]: [6 Mandel params, 3 kp_rot]
    confidence: float          # effective blend weight w_eff: action = (1-w)*rl + w*prior


BACKEND_DEFAULTS = {
    "openai": "gpt-4o-mini",
    "ollama": "llama3.2",
}


class LLMImpedancePlanner:
    """
    Periodically queries an LLM to select an impedance mode based on
    task state description. Between queries, holds last suggestion.

    If `profile_path` is provided, loads modes and system prompt from that
    YAML file (generated by profile_generator.py).  Otherwise falls back to
    the built-in Wipe modes for backwards compatibility.

    Prior-weight schedule
    ─────────────────────
    The effective w is computed per-step (see module docstring for details).
    Key parameters:
      anneal_steps          : If >0, linearly decay w from prior_weight down to
                              anneal_floor over this many per-env planner steps.
                              Set to ~ 0.75 * total_steps / n_envs so the prior
                              fades before the end of training.
      anneal_floor          : Minimum w after annealing (default 0.05). The prior
                              never fully disappears — this small residual provides
                              soft regularization during late-training entropy spikes.
                              Set to 0.0 to anneal completely to zero.
      transition_boost_mult : Temporary multiplier on w for `transition_boost_steps`
                              steps after a phase change.
      transition_boost_steps: How many steps to hold the boost.
      n_stable_reduce       : After this many consecutive same-phase steps, start
                              gently reducing w (floored at anneal_floor).
    """

    def __init__(
        self,
        backend: str = "openai",
        model: str | None = None,
        query_every_n_steps: int = 50,
        prior_weight: float = 0.4,
        profile_path: str | None = None,
        use_spd_manifold: bool = True,
        use_vision: bool = False,
        image_size: tuple = (224, 224),
        # ── Prior-weight schedule ──────────────────────────────────────────
        anneal_steps: int = 0,
        anneal_floor: float = 0.05,
        anneal_schedule: str = "linear",
        transition_boost_mult: float = 1.5,
        transition_boost_steps: int = 10,
        n_stable_reduce: int = 20,
    ):
        self.model = model or BACKEND_DEFAULTS[backend]
        self.query_every = query_every_n_steps
        self.prior_weight = prior_weight
        self.use_vision = use_vision
        self.image_size = image_size

        # ── Schedule params ────────────────────────────────────────────────
        self.anneal_steps = anneal_steps
        self.anneal_floor = anneal_floor   # w never drops below this value
        self.anneal_schedule = anneal_schedule  # "linear" or "cosine"
        self.transition_boost_mult = transition_boost_mult
        self.transition_boost_steps_duration = transition_boost_steps
        self.n_stable_reduce = n_stable_reduce

        # ── Per-step counters (persist across episodes) ────────────────────
        self._global_step: int = 0      # total planner steps across all episodes

        # ── Per-episode counters ───────────────────────────────────────────
        self._step: int = 0             # steps since last episode reset
        self._query_in_flight: bool = False
        self._ep_query_count: int = 0
        self._ep_total_llm_time: float = 0.0
        self._last_latency: float = 0.0

        # ── Phase-tracking state ───────────────────────────────────────────
        self._consecutive_same_phase: int = 0
        self._transition_boost_remaining: int = 0
        self._prev_returned_mode: str = ""
        self._phase_transitions: int = 0
        self._current_phase_duration: int = 0
        self._phase_duration_history: list[int] = []

        # ── Conversation history ───────────────────────────────────────────
        self._history: list[dict] = []

        if profile_path is not None:
            raw_modes, self._system_prompt = _load_profile(profile_path)
            print(
                f"[LLMImpedancePlanner] Loaded profile from {profile_path} "
                f"({len(raw_modes)} phases: {list(raw_modes.keys())}) "
                f"spd={use_spd_manifold} vision={use_vision} "
                f"anneal_steps={anneal_steps} anneal_floor={anneal_floor}."
            )
        else:
            print("[LLMImpedancePlanner] No profile_path provided, exiting...")
            return

        self._modes = _build_modes(raw_modes, use_spd_manifold)
        self._mode_names = list(self._modes.keys())
        self._last = self._default_suggestion()
        self._prev_returned_mode = self._mode_names[0]

        if backend == "ollama":
            ollama_host = os.environ.get("OLLAMA_HOST", "127.0.0.1:11434")
            dynamic_base_url = f"http://{ollama_host}/v1"
            print(f"[LLMImpedancePlanner] Ollama hosted at {dynamic_base_url}")
            self.client = OpenAI(base_url=dynamic_base_url, api_key="ollama")
        else:
            self.client = OpenAI()

    # ── Effective prior weight ─────────────────────────────────────────────────

    def _compute_effective_w(self) -> float:
        """Compute the effective prior weight for the current step.

        Applies annealing (with floor), phase-transition boost, and stability
        reduction in order. The result is always clipped to [0, 1].

        Schedules (anneal_steps=T, floor=w_min):

          linear:  prior_weight ┤━╮
                                │  ╲
                   anneal_floor ┤──╰━━━━━━━━━━  (stays at floor after T)
                                0              T

          cosine:  prior_weight ┤━╮
                                │  ╰╮
                                │    ╰─╮
                   anneal_floor ┤─────╰━  (smooth S-curve, reaches floor at T)
                                0        T
        """
        import math
        w = float(self.prior_weight)

        # 1. Annealing with floor — linear or cosine schedule
        if self.anneal_steps > 0:
            t = self._global_step
            T = self.anneal_steps
            if self.anneal_schedule == "cosine":
                # Cosine annealing: slow start, fast middle, slow end.
                # Reaches anneal_floor exactly at t=T; clamps at floor after.
                progress = min(1.0, t / T)
                anneal_factor = 0.5 * (1.0 + math.cos(math.pi * progress))
            else:
                # Linear (default)
                anneal_factor = max(0.0, 1.0 - t / T)
            # Interpolate between floor and prior_weight
            w = self.anneal_floor + (w - self.anneal_floor) * anneal_factor

        # 2. Phase-transition boost
        # if self._transition_boost_remaining > 0:
        #     w = min(1.0, w * self.transition_boost_mult)
        #     self._transition_boost_remaining -= 1

        # 3. Stability reduction
        # elif self._consecutive_same_phase > self.n_stable_reduce:
        #     excess = self._consecutive_same_phase - self.n_stable_reduce
        #     reduction = max(0.5, 1.0 - 0.005 * excess)
        #     w = max(self.anneal_floor, w * reduction)

        return float(np.clip(w, 0.0, 1.0))

    # ── LLM communication ──────────────────────────────────────────────────────

    def _parse_mode_string(self, mode_str: str) -> str:
        """Robustly extract mode name from potentially messy LLM output."""
        mode_str = re.sub(r'[^\w\s]', '', mode_str).strip().lower()

        if mode_str in self._modes:
            return mode_str
        for known_mode in self._mode_names:
            if known_mode in mode_str:
                return known_mode
        first_word = mode_str.split()[0] if mode_str else ""
        if first_word in self._modes:
            return first_word
        return self._mode_names[0]

    def _encode_image_to_base64(self, image_array: np.ndarray) -> str:
        """Convert numpy image array to base64 JPEG for API submission."""
        if Image is None:
            print("[LLMImpedancePlanner] PIL not installed, skipping image encoding")
            return ""
        try:
            if image_array.dtype in (np.float32, np.float64):
                image_array = (np.clip(image_array, 0, 1) * 255).astype(np.uint8)
            else:
                image_array = np.clip(image_array, 0, 255).astype(np.uint8)

            if image_array.shape[:2] != self.image_size:
                image_pil = Image.fromarray(image_array)
                image_pil = image_pil.resize(self.image_size, Image.Resampling.LANCZOS)
            else:
                image_pil = Image.fromarray(image_array)

            buffered = io.BytesIO()
            image_pil.save(buffered, format="JPEG", quality=85)
            return base64.b64encode(buffered.getvalue()).decode()
        except Exception as e:
            print(f"[LLMImpedancePlanner] Image encoding failed: {e}")
            return ""

    def _fetch_async(self, state_desc: str):
        """Runs in a background thread. Updates self._last when done."""
        start_time = time.time()
        user_msg = f"Current robot state:\n{state_desc}\n\nWhich impedance mode?"
        history_snapshot = self._history + [{"role": "user", "content": user_msg}]
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                max_tokens=20,
                temperature=0,
                messages=[{"role": "system", "content": self._system_prompt}] + history_snapshot,
            )
            mode_str = response.choices[0].message.content.strip().lower()
            mode_str = self._parse_mode_string(mode_str)
            print(f"[LLMImpedancePlanner] LLM → '{mode_str}' in {time.time() - start_time:.2f}s")
            if mode_str not in self._modes:
                mode_str = self._mode_names[0]
        except Exception as e:
            print(f"[LLMImpedancePlanner] Query failed: {e}")
            mode_str = self._last.mode

        latency = time.time() - start_time
        self._last_latency = latency
        self._ep_total_llm_time += latency
        self._ep_query_count += 1

        self._history = history_snapshot + [{"role": "assistant", "content": mode_str}]
        if len(self._history) > 20:
            self._history = self._history[-20:]

        m = self._modes[mode_str]
        # Note: confidence is set to prior_weight (base); _compute_effective_w
        # adjusts it at query-return time in the main thread.
        self._last = ImpedanceSuggestion(
            mode=mode_str,
            action_prior=m["action_prior"].copy(),
            confidence=self.prior_weight,
        )
        self._query_in_flight = False

    def _fetch_async_vision(
        self,
        state_desc: str,
        wrist_image: np.ndarray | None = None,
        view_image: np.ndarray | None = None,
    ):
        """Runs in a background thread with vision. Updates self._last when done."""
        start_time = time.time()
        try:
            if wrist_image is not None or view_image is not None:
                user_content: list[dict] = [
                    {"type": "text", "text": f"Current robot state:\n{state_desc}\n\nAnalyze the images and select the best impedance mode."}
                ]
                for img_arr, label in [(wrist_image, "wrist"), (view_image, "scene")]:
                    if img_arr is not None:
                        img_b64 = self._encode_image_to_base64(img_arr)
                        if img_b64:
                            user_content.append({
                                "type": "image_url",
                                "image_url": {"url": f"data:image/jpeg;base64,{img_b64}", "detail": "low"}
                            })
                messages = (
                    [{"role": "system", "content": self._system_prompt}]
                    + self._history
                    + [{"role": "user", "content": user_content}]
                )
            else:
                user_msg = f"Current robot state:\n{state_desc}\n\nWhich impedance mode?"
                messages = (
                    [{"role": "system", "content": self._system_prompt}]
                    + self._history
                    + [{"role": "user", "content": user_msg}]
                )

            response = self.client.chat.completions.create(
                model=self.model,
                max_tokens=20,
                temperature=0,
                messages=messages,
            )
            mode_str = response.choices[0].message.content.strip().lower()
            mode_str = self._parse_mode_string(mode_str)
            if mode_str not in self._modes:
                mode_str = self._mode_names[0]
        except Exception as e:
            print(f"[LLMImpedancePlanner] VLM query failed: {e}")
            mode_str = self._last.mode

        latency = time.time() - start_time
        self._last_latency = latency
        self._ep_total_llm_time += latency
        self._ep_query_count += 1

        self._history.append({"role": "user", "content": "images received"})
        self._history.append({"role": "assistant", "content": mode_str})
        if len(self._history) > 20:
            self._history = self._history[-20:]

        m = self._modes[mode_str]
        self._last = ImpedanceSuggestion(
            mode=mode_str,
            action_prior=m["action_prior"].copy(),
            confidence=self.prior_weight,
        )
        self._query_in_flight = False

    # ── Public interface ───────────────────────────────────────────────────────

    def _default_suggestion(self) -> ImpedanceSuggestion:
        first = self._mode_names[0]
        m = self._modes[first]
        return ImpedanceSuggestion(first, m["action_prior"].copy(), self.prior_weight)

    def _build_state_description(self, obs_dict: dict) -> str:
        """Convert obs dict to text for the LLM. Handles both Wipe and PiH keys."""
        lines = []

        eef_pos = obs_dict.get("robot0_eef_pos", np.zeros(3))
        lines.append(f"EEF position (xyz): [{eef_pos[0]:.3f}, {eef_pos[1]:.3f}, {eef_pos[2]:.3f}]")

        contact = bool(obs_dict.get("robot0_contact", obs_dict.get("is_contact", False)))
        lines.append(f"In contact: {contact}")

        if self._prev_returned_mode:
            lines.append(f"Previously selected phase: {self._prev_returned_mode}")

        if "proportion_wiped" in obs_dict:
            pw = float(obs_dict["proportion_wiped"])
            lines.append(f"Wipe completion: {pw * 100:.1f}%")
            dist = float(np.linalg.norm(obs_dict.get("gripper_to_wipe_centroid", np.zeros(3))))
            lines.append(f"Distance to wipe centroid: {dist:.4f} m")

        if "peg_head_pos" in obs_dict:
            ph = np.array(obs_dict["peg_head_pos"])
            lines.append(f"Peg head vs hole: [{ph[0]:.3f}, {ph[1]:.3f}, {ph[2]:.3f}]")
        if "insertion_depth" in obs_dict:
            lines.append(f"Insertion depth (0=none, 1=full): {obs_dict['insertion_depth']:.3f}")

        # Door-specific observations
        if "door_pos" in obs_dict:
            dp = np.array(obs_dict.get("door_pos", np.zeros(3)))
            lines.append(f"Door position (xyz): [{dp[0]:.3f}, {dp[1]:.3f}, {dp[2]:.3f}]")
        if "handle_pos" in obs_dict:
            hp = np.array(obs_dict.get("handle_pos", np.zeros(3)))
            lines.append(f"Handle position (xyz): [{hp[0]:.3f}, {hp[1]:.3f}, {hp[2]:.3f}]")
        if "door_to_eef_pos" in obs_dict:
            de = np.array(obs_dict.get("door_to_eef_pos", np.zeros(3)))
            lines.append(f"EEF to handle offset (xyz): [{de[0]:.3f}, {de[1]:.3f}, {de[2]:.3f}]")

        return "\n".join(lines)

    def query(
        self,
        obs_dict: dict,
        wrist_image: np.ndarray | None = None,
        view_image: np.ndarray | None = None,
    ) -> ImpedanceSuggestion:
        """Non-blocking query. Returns last suggestion with effective prior weight.

        Phase tracking is updated in the main thread (here) to avoid race conditions.
        """
        self._step += 1
        self._global_step += 1

        # ── Phase-change tracking (main thread, no lock needed) ────────────
        current_mode = self._last.mode
        if current_mode != self._prev_returned_mode:
            # Phase transition detected
            self._phase_transitions += 1
            if self._current_phase_duration > 0:
                self._phase_duration_history.append(self._current_phase_duration)
            self._current_phase_duration = 0
            self._consecutive_same_phase = 0
            self._transition_boost_remaining = self.transition_boost_steps_duration
        else:
            self._consecutive_same_phase += 1
            self._current_phase_duration += 1
        self._prev_returned_mode = current_mode

        # ── Fire async LLM query if due ────────────────────────────────────
        if self._step % self.query_every == 0 and not self._query_in_flight:
            self._query_in_flight = True
            state_desc = self._build_state_description(obs_dict)
            if self.use_vision and (wrist_image is not None or view_image is not None):
                t = threading.Thread(
                    target=self._fetch_async_vision,
                    args=(state_desc, wrist_image, view_image),
                    daemon=True,
                )
            else:
                t = threading.Thread(target=self._fetch_async, args=(state_desc,), daemon=True)
            t.start()

        # ── Compute effective w and return ─────────────────────────────────
        effective_w = self._compute_effective_w()
        return ImpedanceSuggestion(
            mode=self._last.mode,
            action_prior=self._last.action_prior,
            confidence=effective_w,
        )

    def reset(self):
        """Call at episode start to reset per-episode context.

        Intentionally does NOT reset _global_step — that tracks total training
        progress for the annealing schedule.
        """
        self._history = []
        self._last = self._default_suggestion()
        self._step = 0
        self._query_in_flight = False

        # Per-episode LLM stats
        self._ep_query_count = 0
        self._ep_total_llm_time = 0.0
        self._last_latency = 0.0

        # Per-episode phase tracking
        self._consecutive_same_phase = 0
        self._transition_boost_remaining = 0
        self._prev_returned_mode = self._mode_names[0] if self._mode_names else ""
        self._phase_transitions = 0
        self._current_phase_duration = 0
        self._phase_duration_history = []

    @property
    def mode_names(self) -> list[str]:
        return self._mode_names

    def get_episode_stats(self) -> dict:
        """Return per-episode stats for logging. Call at episode end (on done)."""
        avg_latency = (
            self._ep_total_llm_time / self._ep_query_count
            if self._ep_query_count > 0 else 0.0
        )
        # Include any in-progress phase duration in the average
        all_durations = self._phase_duration_history + (
            [self._current_phase_duration] if self._current_phase_duration > 0 else []
        )
        avg_phase_duration = float(np.mean(all_durations)) if all_durations else 0.0

        return {
            "llm/total_queries":           self._ep_query_count,
            "llm/total_latency_seconds":   self._ep_total_llm_time,
            "llm/avg_latency_seconds":     avg_latency,
            "llm/phase_transitions":       self._phase_transitions,
            "llm/avg_phase_duration_steps": avg_phase_duration,
            "llm/effective_prior_weight":  self._compute_effective_w(),
        }
